pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'pwd'
                sh 'make build'
            }
        }
        stage('Test') {
            steps {
                sh 'pwd'
                sh 'make test'
            }
        }
        stage('Run') {
            steps {
                sh 'pwd'
                sh 'make build'
            }
        }
        stage('Clean') {
            steps {
                sh 'pwd'
                sh 'make clean'
            }
        }
    }
}